const permissionFunction = {
  // POSTS: 'posts',
  // USER: 'user',
  // SCHEMA: 'schema',
  // CATEGORIES: 'categories',
  // PAGES: 'pages',
  // LINK:'link',
  // MEDIA: 'meida',
  // BANNER: 'banner',
  // STATIC: 'static',
  // FAQS: 'faqs'
  BANNER: "banner",
  PANEL: "panel",
  CACHE: "cache",
  DEALER: "dealer",
  DEALERINFOR: "dealerInfor",
  DEALERPAYMENT: "dealerPayment",
  DEALERPROMOTION: "dealerPromotion",
  DEALERSERVICE: "dealerService",
  DOMAIN: "domain",
  FAQ: "faq",
  LEAGUEPROFILE: "leagueProfile",
  LINKFOOTER: "linkFooter",
  LOG: "log",
  PAGE: "page",
  PERMISSION: "permission",
  POST: "post",
  ROLE: "role",
  SCHEMA: "schema",
  TAXONOMY: "taxonomy",
  TEAMPROFILE: "teamProfile",
  USER: "user",
};

module.exports = permissionFunction;
